# Generated by Django 2.0.1 on 2018-03-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('technicalDetails', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('keyWords', models.CharField(max_length=100)),
                ('associatedProjects', models.TextField()),
                ('examplesAndActivities', models.TextField()),
                ('pedagogicStrategy', models.CharField(max_length=100)),
                ('officialDocs', models.CharField(max_length=100)),
                ('associatedTutorials', models.TextField()),
            ],
        ),
    ]
