# Generated by Django 2.0.3 on 2018-04-19 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='home.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='PedagogicStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='home.Example')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('url_site', models.CharField(default='', max_length=120, null=True)),
                ('url_download', models.CharField(default='', max_length=300)),
                ('usage_restrictions', models.CharField(default='', max_length=1000)),
                ('license_type', models.CharField(default='Abierta', max_length=100)),
                ('version', models.CharField(default='1.0', max_length=100)),
                ('key_words', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('integration_lms', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('objective', models.TextField(null=True)),
                ('url', models.URLField(max_length=400)),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='home.Tool')),
            ],
        ),
        migrations.AddField(
            model_name='example',
            name='pedagogic_strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='home.PedagogicStrategy'),
        ),
        migrations.AddField(
            model_name='example',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='home.Tool'),
        ),
    ]
