# Generated by Django 2.0.3 on 2018-04-15 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='home.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='PedagogicStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='home.Example')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('objective', models.TextField(null=True)),
                ('url', models.URLField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='tool',
            name='associatedProjects',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='associatedTutorials',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='examplesAndActivities',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='officialDocs',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='pedagogicStrategy',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='technicalDetails',
        ),
        migrations.AddField(
            model_name='tool',
            name='integrationLms',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='licenseType',
            field=models.CharField(default='Abierta', max_length=100),
        ),
        migrations.AddField(
            model_name='tool',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tool',
            name='urlDownload',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='tool',
            name='urlSite',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='usageRestrictions',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='tool',
            name='version',
            field=models.CharField(default='1.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tool',
            name='keyWords',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Tool'),
        ),
        migrations.AddField(
            model_name='example',
            name='pedagogic_strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='home.PedagogicStrategy'),
        ),
    ]
