# Generated by Django 2.0.3 on 2018-04-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='operative_systems',
            field=models.CharField(default='', max_length=100),
        ),
    ]
