# Generated by Django 2.0.3 on 2018-04-16 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180416_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='tool',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='home.Tool'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='home.Tool'),
        ),
    ]
