# Generated by Django 2.0.2 on 2018-04-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PedagogicStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='tool',
            name='associatedProjects',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='associatedTutorials',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='examplesAndActivities',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='officialDocs',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='pedagogicStrategy',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='technicalDetails',
        ),
        migrations.AddField(
            model_name='tool',
            name='integrationLms',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tool',
            name='licenseType',
            field=models.CharField(default='Abierta', max_length=100),
        ),
        migrations.AddField(
            model_name='tool',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tool',
            name='urlDownload',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='tool',
            name='urlSite',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tool',
            name='usageRestrictions',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='tool',
            name='version',
            field=models.CharField(default='1.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
