# Generated by Django 2.0.3 on 2018-04-19 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180416_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='home.Tool'),
        ),
        migrations.AlterField(
            model_name='pedagogicstrategy',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
